export enum RepositoryToken {
  USERS_REPOSITORY = 'USERS_REPOSITORY',
  TRANSACTIONS_REPOSITORY = 'TRANSACTIONS_REPOSITORY',
  RECURRING_TRANSACTIONS_REPOSITORY = 'RECURRING_TRANSACTIONS_REPOSITORY',
}
