# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: pfa-development
      DB_NAME: personal_finances_test
      DB_HOSTNAME: localhost
      DB_PORT: 5432
      JWT_SECRET: test_secret
      JWT_EXPIRES_IN: 1d

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pfa-development
          POSTGRES_USER: postgres
          POSTGRES_DB: personal_finances_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn

      - name: Run migrations
        run: yarn migration:run:test

      - name: Run tests
        run: yarn test
